version: 2
updates:
  - package-ecosystem: npm
    directory: "/agent"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/proxy"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/npms/skale-ima"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/npms/skale-cool-socket"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/npms/skale-observer"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/npms/skale-owasp"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/test"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: "/npms/test-tokens"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 3
