[[section-runtime-view]]
== Runtime View

=== <Runtime Scenario 1: Network discovery>

.Network discovery

[plantuml, target="network-discovery", format="png"]
....
@startuml
participant "IMA Agent"
participant "SKALED 0"
participant "SKALED 1"
participant "SKALED 2"
participant "SKALED N"
    "IMA Agent" -> "SKALED 0" : Query S-Chain network information
    "SKALED 0" -> "IMA Agent": S-Chain network description
    "IMA Agent" -> "SKALED 0" : Query BLS information
    "SKALED 0" -> "IMA Agent": BLS public keys
    "IMA Agent" -> "SKALED 1" : Query BLS information
    "SKALED 1" -> "IMA Agent": BLS public keys
    "IMA Agent" -> "SKALED 2" : Query BLS information
    "SKALED 2" -> "IMA Agent": BLS public keys
    "IMA Agent" -> "SKALED N" : Query BLS information
    "SKALED N" -> "IMA Agent": BLS public keys
@enduml
....

`IMA Agent` needs information about all S-Chain `SKALED` nodes to work. So, first task on startup is to gather S-Chain network information. All the `IMA Agents` and all `SKALED` instances are numbered. For instance, in a `16` node S-Chain they are numbered from `0` to `15`. Each `IMA Agent` queries `SKALED` for network addresses of all `SKALED` instances in same S-Chain. In case of network connectivity problems, this query is repeated unlimited number of attempts. Next, `IMA Agent` queries each `SKALED` instance for `BLS public keys`. At least `2 / 3` of `BLS public keys` are needed to continue work. This means `11` of `SKALED` instances of 16 must provide `BLS public keys` to let `IMA Agent` operate normally. `IMA Agent` starts after that. `IMA Agent` continues to attemt to get `BLS piblic keys` from all `SKALED` nodes parallel of some of them have network connectivity problems at startup time.

=== <Runtime Scenario 2: Agent time framing>

.Agent time framing

[plantuml, target="agent-time-framing", format="png"]
....
@startuml
participant "Main Net"
participant "IMA Agent 0"
participant "IMA Agent 1"
participant "IMA Agent 2"
participant "IMA Agent N"
participant "SKALED 0"
participant "SKALED 1"
participant "SKALED 2"
participant "SKALED N"
    "Main Net" -> "IMA Agent 0" : Message transfers from Main Net to S-Chain
    "IMA Agent 0" -> "SKALED 0" : Message transfers from Main Net to S-Chain
    "SKALED 0" -> "IMA Agent 0" : Message transfers from S-Chain to Main Net
    "IMA Agent 0" -> "Main Net" : Message transfers from S-Chain

    "Main Net" -> "IMA Agent 1" : Message transfers from Main Net to S-Chain
    "IMA Agent 1" -> "SKALED 1" : Message transfers from Main Net to S-Chain
    "SKALED 1" -> "IMA Agent 1" : Message transfers from S-Chain to Main Net
    "IMA Agent 1" -> "Main Net" : Message transfers from S-Chain
    
    "Main Net" -> "IMA Agent 2" : Message transfers from Main Net to S-Chain
    "IMA Agent 2" -> "SKALED 2" : Message transfers from Main Net to S-Chain
    "SKALED 2" -> "IMA Agent 2" : Message transfers from S-Chain to Main Net
    "IMA Agent 2" -> "Main Net" : Message transfers from S-Chain
    
    "Main Net" -> "IMA Agent N" : Message transfers from Main Net to S-Chain
    "IMA Agent N" -> "SKALED N" : Message transfers from Main Net to S-Chain
    "SKALED N" -> "IMA Agent N" : Message transfers from S-Chain to Main Net
    "IMA Agent N" -> "Main Net" : Message transfers from S-Chain
    
@enduml
....

`IMA Agents` do not work all together at a same time. They work one by one sequentially equal period of times we call `time frames`. Each `IMA Agent` computes its time frame so all `IMA Agents` cover time line one by one. `Time frame` computed correctly because `IMA Agent` knows its `index`. `Time frames` start on 1st January 1970 and usually `5` minutes long. `IMA Agent` does Main Net to S-Chain message transers, S-Chain to Main Net transfers and pause. Then it repeats its work.

=== <Runtime Scenario 3: Main Net to S-Chain transfer>

.Main Net to S-Chain transfer

[plantuml, target="main-net-to-s-chain-transfer", format="png"]
....
@startuml
participant "IMA Agent"
participant "Main Net"
participant "SKALED"
participant "Transacton Manager"
participant "SGX Wallet"
    "IMA Agent" -> "Main Net" : Query outgoing message counter
    "IMA Agent" -> "SKALED" : Query incoming message counter
    "IMA Agent" -> "Main Net" : Query new messages to transfer
    "IMA Agent" -> "SKALED" : Verify messages
    "SKALED" -> "Main Net": Search contract events 
    "SKALED" -> "SKALED" : Analyze message correctness
    "SKALED" -> "Transacton Manager": BLS sign messages
    "Transacton Manager" -> "SGX Wallet": BLS sign messages
    "SGX Wallet" -> "Transacton Manager": BLS signature
    "Transacton Manager" -> "SKALED": BLS signature
    "SKALED" -> "IMA Agent": partial BLS signature
    "IMA Agent" -> "IMA Agent": verify partial BLS signature
    "IMA Agent" -> "IMA Agent": BLS glue
    "IMA Agent" -> "SKALED": submit BLS signed incoming message
@enduml
....

Let's review Main Net to S-Chain transfer:

- `IMA Agent` queries `outgoing message counter` on Main Netand `incoming message counter` on S-Chain. First can be greater or equal than second. If greater, then new messages are ready to transfer.
- `IMA Agent` queries message data for all new messages one by one. Messages are organized into groups up to `4` messages in group for further signing.
- `IMA Agent` calls `SKALED` to verify and sign group of messages.
- `SKALED` queries Main Net for smart contract events and verifies messages are correct and can be delivered to S-Chain.
- `SKALED` queries `Transaction Manager` to sign messages, `Transaction Manager` passes work to `SGX Wallet`, - `SKALED` obtains partial BLS signature and returns it to `IMA Agent`.
- `IMA Agent` collects partial BLS signatures from at least `2/3` of `SKALED` nodes, verifies each partial BLS sigature, performs BLS siganture glue.
- `IMA Agent` submits messages with summary BLS signature to S-Chain.

