= Development with IMA-SDK

IMA-SDK is a tool for dApp developers that emulates SKALE Node + IMA env on a single machine for dev purposes.  
This article will demonstrate how to setup and use the IMA-SDK in combination with IMA-JS library for dApp development.

== SDK setup

=== Prerequisites

* Docker
* docker-compose
* nodejs (any version)

=== 1. Clone IMA-SDK repo

```bash
https://github.com/skalenetwork/skale-ima-sdk.git
```

=== 2. Copy .env template and fill variables

```bash
cp .env-compose-sample .env
nano .env
```
=== 3. Export environment variables

```bash
export $(grep -v '^#' .env | xargs)
```

=== 4. Setup SSL certs (optional)

[NOTE]
This step is optional. You should have SSL certs, domain name and setup redirects by yourself.
  
Put SSL cert & key to `ssl` folder (names should be `ssl_key` and `ssl_cert`):

```bash
cp privkey.pem ~/skale-ima-sdk/ssl/ssl_key
cp cert.pem ~/skale-ima-sdk/ssl/ssl_cert
```

=== 5. Add additional accounts (optional)

[NOTE]
This step is optional. Proceed to the next step if you need only 1 account with funds.

You can pass any number of additional accounts to the SDK.  
All accounts will have pre-allocated ETH both on Mainnet and sChain sides. 
To do that add `additional_accounts.json` file in the root of the project. Structure of the file:

```json
[
    {
        "private_key": "0x...",
        "address": "0x.."
    },
    {
        "private_key": "0x...",
        "address": "0x.."
    }
    ...
]
```

=== 6. Run SDK

```bash
WAIT=True bash scripts/run_sdk.sh
```

Wait till contracts will be deployed to the Mainnet and sChain parts.  

Now sChain and Mainnet parts are available:

```bash
# sChain
http://$IP_ADDRESS:15000
http://$DOMAIN_NAME/schain # if you have SSL certs and domain name
https://$DOMAIN_NAME/schain # if you have SSL certs and domain name

# Mainnet
http://$IP_ADDRESS:1545
http://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
https://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
```

When you're done, stop SDK:

```bash
CLEANUP=True  bash scripts/stop_sdk.sh
```

== IMA-JS integration

Now, once you have IMA-SDK up running, it's time try some interchain transfers!

[NOTE]
In all ima-js code samples we're assuming that library is already inited. See init instructions xref:working-with-ima-js.adoc[here]. For the 2 objects usage drop `ima.` prefix.

=== 1. Connect chain, grant admin permissions

First of all you should connect your chain to the Mainnet contracts:

```javascript

```


