= Development with IMA-SDK

IMA-SDK is a tool for dApp developers that emulates SKALE Node + IMA env on a single machine for dev purposes.  
This article will demonstrate how to setup and use the IMA-SDK in combination with IMA-JS library for dApp development.

== SDK setup

=== Prerequisites

* Docker
* docker-compose
* nodejs (any version)

=== 1. Clone IMA-SDK repo

```bash
git clone https://github.com/skalenetwork/skale-ima-sdk.git
```

=== 2. Copy .env template and fill variables

```bash
cp .env-compose-sample .env
nano .env
```
=== 3. Export environment variables

```bash
export $(grep -v '^#' .env | xargs)
```

=== 4. Setup SSL certs (optional)

[NOTE]
This step is optional. You should have SSL certs, domain name and setup redirects by yourself.
  
Put SSL cert & key to `ssl` folder (names should be `ssl_key` and `ssl_cert`):

```bash
cp privkey.pem ~/skale-ima-sdk/ssl/ssl_key
cp cert.pem ~/skale-ima-sdk/ssl/ssl_cert
```

=== 5. Add additional accounts (optional)

[NOTE]
This step is optional. Proceed to the next step if you need only 1 account with funds.

You can pass any number of additional accounts to the SDK.  
All accounts will have pre-allocated ETH both on Mainnet and sChain sides. 
To do that add `additional_accounts.json` file in the root of the project. Structure of the file:

```json
[
    {
        "private_key": "0x...",
        "address": "0x.."
    },
    {
        "private_key": "0x...",
        "address": "0x.."
    }
    ...
]
```

=== 6. Run SDK

```bash
WAIT=True bash scripts/run_sdk.sh
```

Wait till contracts will be deployed to the Mainnet and sChain parts.  

Now sChain and Mainnet parts are available:

```bash
# sChain
http://$IP_ADDRESS:15000
http://$DOMAIN_NAME/schain # if you have SSL certs and domain name
https://$DOMAIN_NAME/schain # if you have SSL certs and domain name

# Mainnet
http://$IP_ADDRESS:1545
http://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
https://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
```

When you're done, stop SDK:

```bash
CLEANUP=True  bash scripts/stop_sdk.sh
```

== IMA-JS integration

Now, once you have IMA-SDK up running, it's time try some interchain transfers!

[NOTE]
In all ima-js code samples we're assuming that library is already inited. See init instructions xref:working-with-ima-js.adoc[here]. For the 2 objects usage drop `ima.` prefix.

=== 1. Connect your chain

First of all you should connect your chain to the Mainnet contracts:

```javascript
async function chainSetup(ima) {
    const sdkAddress = helper.privateKeyToAddress(ima.mainnet.web3, SDK_PRIVATE_KEY);
    const opts = {
        address: sdkAddress,
        privateKey: SDK_PRIVATE_KEY
    }
    const isChainConnected = await ima.mainnet.isChainConnected(SCHAIN_NAME);
    if (!isChainConnected){
        await ima.connectSchain(SCHAIN_NAME, opts);
    }
}
```

=== 2. Work with IMA-JS

Once chain is connected you can do anything that you want with your chain!
In this example we will transfer ETH from the Mainnet to the sChain and back.

=== 2.1 Recharge user's reimbursement wallet

```javascript
async function reimburseWallet(ima) {
    let testAddress = helper.privateKeyToAddress(ima.schain.web3, TEST_PRIVATE_KEY);
    let txOpts = {
        value: TEST_WEI_REIMBURSEMENT_VALUE,
        address: testAddress,
        privateKey: TEST_PRIVATE_KEY
    };
    await ima.mainnet.reimbursementWalletRecharge(
        SCHAIN_NAME,
        txOpts
    );
}
```

=== 2.2 Perform transfers

```javascript
async function ethTransferDemo(ima) {
    const address = helper.privateKeyToAddress(ima.mainnet.web3, TEST_PRIVATE_KEY);
    let txOpts = {
        value: TEST_WEI_TRANSFER_VALUE,
        address: address,
        privateKey: TEST_PRIVATE_KEY
    };

    let mainnetBalanceBefore = await ima.mainnet.ethBalance(address);
    let sChainBalanceBefore = await ima.schain.ethBalance(address);

    await ima.mainnet.depositETHtoSChain(
        SCHAIN_NAME,
        address,
        txOpts
    );
    await ima.schain.waitETHBalanceChange(address, sChainBalanceBefore);

    let mainnetBalanceAfterDeposit = await ima.mainnet.ethBalance(address);
    let sChainBalanceAfterDeposit = await ima.schain.ethBalance(address);

    console.log('M -> S transfer complete!');
    console.log('Mainnet balance before deposit: ', mainnetBalanceBefore);
    console.log('sChain balance before deposit: ', sChainBalanceBefore);
    console.log('Mainnet balance after deposit: ', mainnetBalanceAfterDeposit);
    console.log('sChain balance after deposit: ', sChainBalanceAfterDeposit);

    let lockedETHAmount = await ima.mainnet.lockedETHAmount(address);

    await ima.schain.withdrawETH(
        address,
        TEST_WEI_TRANSFER_VALUE,
        {
            address: address,
            privateKey: TEST_PRIVATE_KEY
        }
    );

    await ima.mainnet.waitLockedETHAmountChange(address, lockedETHAmount);
    await ima.mainnet.getMyEth(
        {
            address: address,
            privateKey: TEST_PRIVATE_KEY
        }
    );

    let mainnetBalanceAfterWithdraw = await ima.mainnet.ethBalance(address);
    let sChainBalanceAfterWithdraw = await ima.schain.ethBalance(address);

    console.log('S -> M transfer complete!');
    console.log('Mainnet balance before withdraw: ', mainnetBalanceAfterDeposit);
    console.log('sChain balance before withdraw: ', sChainBalanceAfterDeposit);
    console.log('Mainnet balance after withdraw: ', mainnetBalanceAfterWithdraw);
    console.log('sChain balance after withdraw: ', sChainBalanceAfterWithdraw);
}

async function main() {
    let ima = initIMA();
    const transferValBN = ima.mainnet.web3.utils.toBN(TEST_WEI_TRANSFER_VALUE);

    await chainSetup(ima);
    await reimburseWallet(ima);
    await ethTransferDemo(ima);
}
```

You can find more IMA-JS docs xref:working-with-ima-js.adoc[here].