= Managing ERC20
:sectnumlevels: 5
include::ima-sandboxes.adoc[]


As a SKALE Chain Owner, there are two main steps to managing ERC20 through IMA:

1.  xref:setup[One-time setup and map your ERC20 tokens to your SKALE Chain]
2.  xref:transfer[Transferring ERC20 using IMA]

Once you have completed step 1 to setup and map your ERC20 tokens, you can then setup transfer flow to allow end-users to transfer ERC20 tokens between Ethereum and your SKALE Chain.

[[setup]]
== Setup and Map ERC20 Transfers

The following one-time setup for each ERC20 token is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

To see a complete Javascript sandbox version of setup, map, and transfer, see <{erc20-sandbox}>

=== 1. Review/Modify the token contract

First, review the Mainnet ERC20 token implementation and (if needed) modify a SKALE Chain version of the contract to include Mintable and Burnable functions. These functions are required to dynamically mint and burn the token on the SKALE chain in response to deposit and exit on the Mainnet.

[discrete]
==== Example Mainnet contract

[source,javascript]
----
include::example$base-erc20-contract.sol[]
----

[discrete]
==== Example Modified SKALE Chain contract

[source,javascript]
----
include::example$modified-erc20-contract.sol[]
----

If you aren't using OpenZeppelin's framework, then you can simply manually add https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC20/ERC20.sol#L233[Mintable] and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC20/ERC20.sol#L254[Burnable] functions, and finally https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.5.1/contracts/access/roles/MinterRole.sol[add MINTER_ROLE access control]. 

=== 2. Add a Minter Role

Now you need to add the pre-deployed **TokenManagerERC20** contact on your SKALE Chain as the MINTER_ROLE for the modified SKALE Chain contract. With OpenZeppelin's framework, you simply need to execute an AddMinter transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/add-minter-role.js[]
----
--
====

For a Javascript sandbox of the minter implementation, see <https://codesandbox.io/s/erc20-transfer-skale-interchain-messaging-agent-forked-w1t5m?file=/src/addMinter.js>

=== 3. Register Ethereum Mainnet contract to IMA

Third, you need to register the Ethereum Mainnet token contract into IMA on Ethereum Mainnet using the addERC20TokenByOwner method in the DepositBoxERC20 contract.

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we&#39;re assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc20/register-mainnet-imajs.js[]
----

--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/register-mainnet-web3.js[]
----
--
====

For a Javascript sandbox version of registering contracts on Mainnet, see <https://codesandbox.io/s/erc20-transfer-skale-interchain-messaging-agent-forked-w1t5m?file=/src/addERC20TokenByOwner.js>

=== 4. Register SKALE Chain contract to IMA

Finally, you need to register the (modified) token contract on the SKALE chain IMA using the addERC20TokenByOwner method in TokenManagerERC20 contract. Note that you need to register the contract on Mainnet first, so that the registration on the SKALE Chain can reference the Mainnet token address.

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc20/register-schain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/register-schain-web3.js[]
----
--
====

For a Javascript sandbox version of registering contracts on your SKALE Chain, see <https://codesandbox.io/s/erc20-transfer-skale-interchain-messaging-agent-forked-w1t5m?file=/src/schain_addERC20TokenByOwner.js>

[[view]]
== Show All Mapped Tokens

To view all mapped tokens (including those mapped manually and automatically)

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
let erc20Len = await ima.mainnet.erc20.getTokenMappingsLength(SCHAIN_NAME);
let erc20Tokens = await ima.mainnet.erc20.getTokenMappings(SCHAIN_NAME, 0, erc20Len);
----
--

Web3 JS::
+
--

You can use the getSchainToAllERC20Length() and getSchainToAllERC20() functions to return the length and an array of a set of mapped tokens. Note that getSchainToAllERC20() can only return a maximum set of 10 tokens at a time.


[source,javascript]
----
include::example$erc20/mappings-web3.js[]
----
--

====

[[transfer]]
== Get Started with ERC20 Transfer

The Interchain Messaging Agent can be used for managing ERC20 tokens between Ethereum and SKALE. The following steps guide you through a complete transfer from Ethereum to SKALE and back. Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating transfers.

link:{erc20-sandbox}[Live ERC20 IMA Demo]

=== 1. Deposit ERC20 on Ethereum

To send ERC20 tokens from a user's wallet to the IMA Deposit Box on Ethereum, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/mainnet/DepositBoxes/DepositBoxERC20.sol#L48[depositERC20] function within the **DepositBoxERC20** IMA contract on Ethereum.  

[NOTE]
The depositERC20() requires that the `msg.sender` is the receiver address. For specifying the receiver, use depositERC20Direct().

This method is called from Ethereum to move ERC20 tokens into a Deposit Box.  

The **DepositBoxERC20** contract is on Rinkeby testnet. To get the ABIs to interact with IMA on Rinkeby, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/rinkeby/IMA[current release page].  

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[source, javascript]
----
include::example$erc20/deposit-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/deposit-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To send ERC20 tokens back to Ethereum, you will need to use the exitToMainERC20 function within the **TokenManagerERC20** IMA contract on the SKALE Chain.  

This method is called from the SKALE Chain to send funds and move the token back to Ethereum.  

include::partial$user-exit-requirements.adoc[]

The **TokenManagerERC20** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[source, javascript]
----
include::example$erc20/exit-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/exit-web3.js[]
----
--
====
