= Managing ERC1155
include::ima-sandboxes.adoc[]

As a SKALE Chain Owner, there are two main steps to managing ERC1155 through IMA:

1.  xref:setup[One-time setup and map your ERC1155 tokens to your SKALE Chain]
2.  xref:transfer[Transferring ERC1155 using IMA]

Once you have completed step 1 to setup and map your ERC1155 tokens, you can then setup transfer flow to allow end-users to transfer ERC1155 tokens between Ethereum and your SKALE Chain.

[[setup]]
== Setup and Map ERC1155 Transfers

The following one-time setup for each ERC1155 token is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Review the token contract

First, review the Mainnet ERC1155 token implementation and (if needed) modify a SKALE Chain version of the contract to include Mintable and Burnable functions. These functions are required to dynamically mint and burn the token on the SKALE chain in response to deposit and exit on the Mainnet.

[discrete]
==== Example Mainnet contract

```javascript
pragma solidity 0.6.12;

import "@openzeppelin/contracts-upgradeable/token/ERC1155/ERC1155Burnable.sol";

contract ERC1155OnChain is ERC1155Burnable {

    event MinterAdded(address indexed account);

    constructor(
        string memory uri
    )
        public
        ERC1155(uri)
    {
    }

    function mint(
        address account,
        uint256 id,
        uint256 amount,
        bytes memory data
    )
        public
    {
        _mint(account, id, amount, data);
    }

    function mintBatch(
        address account,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    )
        public
    {
        _mintBatch(account, ids, amounts, data);
    }

    function addMinter(address account) external {
        emit MinterAdded(account);
    }
}
```

[discrete]
==== Example Modified SKALE Chain contract

```javascript
pragma solidity 0.6.12;

import "@openzeppelin/contracts-upgradeable/token/ERC1155/ERC1155Burnable.sol";

contract ERC1155OnChain is ERC1155Burnable {

    event MinterAdded(address indexed account);

    constructor(
        string memory uri
    )
        public
        ERC1155(uri)
    {
    }

    function mint(
        address account,
        uint256 id,
        uint256 amount,
        bytes memory data
    )
        public
    {
        _mint(account, id, amount, data);
    }

    function mintBatch(
        address account,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    )
        public
    {
        _mintBatch(account, ids, amounts, data);
    }

    function addMinter(address account) external {
        emit MinterAdded(account);
    }
}
```

If you aren't using OpenZeppelin's framework, then you can manually add Mintable and Burnable functions, and finally [add MINTER_ROLE access control](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.5.1/contracts/access/roles/MinterRole.sol). Be sure that the main mint and burn functions have `public` visibility with the private _mint and _burn functions as `internal` visibility. 

For a set of examples for IMA SKALE-Chain side suitable tokens, see the https://github.com/skalenetwork/IMA/tree/develop/proxy/test-tokens[IMA test-tokens folder].

=== 2. Add a Minter Role

Now you need to add the pre-deployed TokenManagerERC1155 contact on your SKALE Chain as the MINTER_ROLE for the modified SKALE Chain contract. With OpenZeppelin's framework, you simply need to execute an AddMinter transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--

[source,javascript]
----
include::example$erc1155/add-minter-role.js[]
----
--
====

=== 3. Register Mainnet contract to IMA

Third, you need to register the Mainnet token contract into IMA on Mainnet using the addERC1155TokenByOwner method in the DepositBoxERC1155 contract:

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc1155/register-mainnet-imajs.js[]
----

--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc1155/register-mainnet-web3.js[]
----
--
====

=== 4. Register SKALE Chain contract to IMA

Finally, you need to register the (modified) token contract on the SKALE chain IMA using the addERC1155TokenByOwner method in TokenManagerERC1155 contract. Note that you need to register the contract on Mainnet first, so that the registration on the SKALE Chain can reference the Mainnet token address.

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc1155/register-schain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc1155/register-schain-web3.js[]
----
--
====

[[view]]
== Show All Mapped Tokens

To view all mapped tokens (including those mapped manually and automatically)

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
let erc1155Len = await ima.mainnet.erc1155.getTokenMappingsLength(SCHAIN_NAME);
let allErc1155Tokens = await ima.mainnet.erc1155.getTokenMappings(SCHAIN_NAME, 0, erc1155Len);
----
--

Web3 JS::
+
--

You can use the getSchainToAllERC1155Length() and getSchainToAllERC1155() functions to return the length and an array of a set of mapped tokens. Note that getSchainToAllERC1155() can only return a maximum set of 10 tokens at a time.


[source,javascript]
----
include::example$erc1155/mappings-web3.js[]
----
--

====

[[transfer]]
== Get Started with ERC1155 Transfer

The Interchain Messaging Agent can be used for managing ERC1155 tokens between Ethereum and SKALE.  The following steps guide you through a complete transfer from Ethereum to SKALE and back. Be sure to follow any one-time setup and mapping steps described xref:setup[here].

link:{erc1155-sandbox}[Live ERC1155 IMA Demo: {erc1155-sandbox}]

=== 1. Deposit ERC1155 on Ethereum

To send ERC1155 tokens from a user's wallet to the IMA Deposit Box on Ethereum, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/mainnet/DepositBoxes/DepositBoxERC1155.sol#L74[depositERC1155] function within the **DepositBoxERC1155** IMA contract on Ethereum.

This method is called from Ethereum to move ERC1155 tokens into a Deposit Box.  

The **DepositBoxERC1155** IMA contract is currently deployed to the Rinkeby testnet. To get the ABIs to interact with IMA on Rinkeby, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/rinkeby/IMA[current release page].  

[discrete]
==== Example Code

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[NOTE]
It's also possible to deposit a batch of ERC1155 tokens at once. To do that, just pass `erc1155TokenIds` and `amounts` arrays instead of `erc1155TokenId` and `amount` to `depositERC1155` function.

[source, javascript]
----
include::example$erc1155/deposit-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc1155/deposit-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To send ERC1155 tokens back to Ethereum, you will need to use the exitToMainERC1155 function within the **TokenManagerERC1155** IMA  contract on the SKALE Chain.  

This method is called from the SKALE Chain to send funds and move the token back to Ethereum.  

include::partial$user-exit-requirements.adoc[]

The **TokenManagerERC1155** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[discrete]
==== Example Code

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[NOTE]
It's also possible to withdraw a batch of ERC1155 tokens at once. To do that, just pass `erc1155TokenIds` and `amounts` arrays instead of `erc1155TokenId` and `amount` to `withdrawERC1155` function.

[source, javascript]
----
include::example$erc1155/exit-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc1155/exit-web3.js[]
----
--
====
