= Managing ERC721 and ERC721 with metadata
include::ima-sandboxes.adoc[]

As a SKALE Chain Owner, there are two main steps to managing ERC721 through IMA:

1.  xref:setup[One-time setup and map your ERC721 tokens to your SKALE Chain]
2.  xref:transfer[Transferring ERC721 using IMA]

Once you have completed step 1 to setup and map your ERC721 tokens, you can then setup transfer flow to allow end-users to transfer ERC721 tokens between Ethereum and your SKALE Chain.

NOTE: Please use TokenManagerERC721WithMetadata to transfer ERC721 token with tokenURI, TokenManagerERC721 will transfer ERC721 token without tokenURI. The flow to use TokenManagerERC721WithMetadata is similar to the flow of using TokenManagerERC721

NOTE: In `ima-js` library replace `ima.mainnet.erc721.` and `ima.schain.erc721.` with `ima.mainnet.erc721meta.` and `ima.schain.erc721meta.` to use ERC721 with metadata.

[[setup]]
== Setup and Map ERC721 Transfers

The following one-time setup for each ERC721 token is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Review the token contract

First, review the Mainnet ERC721 token implementation and (if needed) modify a SKALE Chain version of the contract to include Mintable and Burnable functions. These functions are required to dynamically mint and burn the token on the SKALE chain in response to deposit and exit on the Mainnet.

[discrete]
==== Example Mainnet contract

```javascript
pragma solidity >=0.4.24 <0.6.0;

import "@openzeppelin/contracts/token/ERC721/ERC721Full.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721Mintable.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721Burnable.sol";

contract MyERC721 is ERC721Full, ERC721Mintable, ERC721Burnable {
    constructor(
        string memory _name,
        string memory _symbol
    ) 
    ERC721Full(_name, _symbol)
    public 
    {
    }

    /**
    * Custom accessor to create a unique token
    */
    function mintUniqueTokenTo(
        address _to,
        uint256 _tokenId,
        string  memory _tokenURI
    ) public
    {
        super._mint(_to, _tokenId);
        super._setTokenURI(_tokenId, _tokenURI);
    }
}
```

[discrete]
==== Example Modified SKALE Chain contract

```javascript
pragma solidity >=0.4.24 <0.6.0;

import "@openzeppelin/contracts/token/ERC721/ERC721Full.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721Mintable.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721Burnable.sol";

contract MyERC721 is ERC721Full, ERC721Mintable, ERC721Burnable {
    constructor(
        string memory _name,
        string memory _symbol
    ) 
    ERC721Full(_name, _symbol)
    public 
    {
    }

    /**
    * Custom accessor to create a unique token
    */
    function mintUniqueTokenTo(
        address _to,
        uint256 _tokenId,
        string  memory _tokenURI
    ) public
    {
        super._mint(_to, _tokenId);
        super._setTokenURI(_tokenId, _tokenURI);
    }
}
```

If you aren't using OpenZeppelin's framework, then you can manually add [Mintable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC721/ERC721.sol#L256) and [Burnable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC721/ERC721.sol#L278) functions, and finally [add MINTER_ROLE access control](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.5.1/contracts/access/roles/MinterRole.sol). Be sure that the main mint and burn functions have `public` visibility with the private _mint and _burn functions as `internal` visibility. For a further example, see [IMA ERC721 Custom Token](https://github.com/skalenetwork/IMA/blob/develop/proxy/test-tokens/contracts/ERC721Custom.sol).

For a set of examples for IMA SKALE-Chain side suitable tokens, see the https://github.com/skalenetwork/IMA/tree/develop/proxy/test-tokens[IMA test-tokens folder].

=== 2. Add a Minter Role

Now you need to add the pre-deployed TokenManagerERC721 contact on your SKALE Chain as the MINTER_ROLE for the modified SKALE Chain contract. With OpenZeppelin's framework, you simply need to execute an AddMinter transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--

[source,javascript]
----
include::example$erc721/add-minter-role.js[]
----
--
====

=== 3. Register Mainnet contract to IMA

Third, you need to register the Mainnet token contract into IMA on Mainnet using the addERC721TokenByOwner method in the DepositBoxERC721 contract:

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc721/register-mainnet-imajs.js[]
----

--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc721/register-mainnet-web3.js[]
----
--
====

=== 4. Register SKALE Chain contract to IMA

Finally, you need to register the (modified) token contract on the SKALE chain IMA using the addERC721TokenByOwner method in TokenManagerERC721 contract. Note that you need to register the contract on Mainnet first, so that the registration on the SKALE Chain can reference the Mainnet token address.

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  

[source, javascript]
----
include::example$erc721/register-schain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc721/register-schain-web3.js[]
----
--
====

[[view]]
== Show All Mapped Tokens

To view all mapped tokens (including those mapped manually and automatically)

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
let erc721Len = await ima.mainnet.erc721.getTokenMappingsLength(SCHAIN_NAME);
let allErc721Tokens = await ima.mainnet.erc721.getTokenMappings(SCHAIN_NAME, 0, erc721Len);
----
--

Web3 JS::
+
--

You can use the getSchainToAllERC721Length() and getSchainToAllERC721() functions to return the length and an array of a set of mapped tokens. Note that getSchainToAllERC721() can only return a maximum set of 10 tokens at a time.


[source,javascript]
----
include::example$erc721/mappings-web3.js[]
----
--

====

[[transfer]]
== Get Started with ERC721 Transfer

The Interchain Messaging Agent can be used for managing ERC721 tokens between Ethereum and SKALE.  The following steps guide you through a complete transfer from Ethereum to SKALE and back. Be sure to follow any one-time setup and mapping steps described xref:setup[here].

{erc721-sandbox}[Live ERC721 IMA Demo: {erc721-sandbox}]

=== 1. Deposit ERC721 on Ethereum

To send ERC721 tokens from a user's wallet to the IMA Deposit Box on Ethereum, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/mainnet/DepositBoxes/DepositBoxERC721.sol#L43[depositERC721] function within the **DepositBoxERC721** IMA contract on Ethereum.

This method is called from Ethereum to move ERC721 tokens into a Deposit Box.  

The **DepositBoxERC721** IMA contract is currently deployed to the Rinkeby testnet. To get the ABIs to interact with IMA on Rinkeby, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/rinkeby/IMA[current release page].  

[discrete]
==== Example Code

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[source, javascript]
----
include::example$erc721/deposit-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$erc721/deposit-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To send ERC721 tokens back to Ethereum, you will need to use the exitToMainERC721 function within the **TokenManagerERC721** IMA  contract on the SKALE Chain.  

This method is called from the SKALE Chain to send funds and move the token back to Ethereum.  

include::partial$user-exit-requirements.adoc[]

The **TokenManagerERC721** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[discrete]
==== Example Code

[tabs]
====
IMA-JS::
+
--

In all ima-js code samples we're assuming that library is already inited. See init instructions xref:ima-js-overview.adoc[here]. For the 2 objects usage drop `ima.` prefix.  
link:{eth-ima-js-sandbox}?file=/src/deposit.js[See IMA-JS deposit.js sandbox]

[source, javascript]
----
include::example$erc721/exit-imajs.js[]
----
--


Web3 JS::
+
--

[source,javascript]
----
include::example$erc721/exit-web3.js[]
----
--
====
