= SKALE Chain to SKALE Chain ERC20 Transfer

As a SKALE Chain Owner, there are two main steps to managing SKALE Chain to SKALE Chain (S2S) ERC20 transfer through IMA:

1.  xref:setup[One-time setup to another SKALE Chain]
2.  xref:transfer[Transferring ERC20 S2S]

Once you have completed step 1 to setup ERC20 tokens with another chain, end-users can transfer ERC20 tokens between SKALE Chains.

[[setup]]
== Setup ERC20 S2S Transfers

The following one-time setup is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Connect each SKALE Chain

You must connect each chain in both directions by executing two connectSchain() transaction on each respective chain.

⇢ To connect the `target` chain to the `origin` chain, run `connectSchain(targetSchainName)` in **TokenManagerLinker** contract on the `origin` chain. 

⇠ To connect the `origin` chain to the `target` chain, run `connectSchain(originSchainName)` in **TokenManagerLinker** contract on the `target` chain.

[NOTE]
Only the `REGISTRAR_ROLE` in TokenManagerLinker may execute `connectSchain`. So you must be granted with this role on this contract.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-web3.js[]
----
--
====

=== 2. Deploy ERC20 on Origin

Deploy your ERC20 contract on the Origin chain.

[source,javascript]
----
include::example$erc20/token.sol[]
----

=== 3. Deploy ERC20 clone on Target

The ERC20 clone on the target chain MUST have both mint and burn functionalities. If the original ERC20 contract on origin does not have burn functionalities, then you must either assign `BURNER_ROLE` (if using Open Zeppelin's Role-Based Access control) or add a burn() to the clone that is assigned/callable by the TokenManagerERC20.

[source,javascript]
----
include::example$erc20/token-clone.sol[]
----

=== 4. Register ERC20 clone in TokenManger on Target

You need to register the target token contract using the addERC20TokenByOwner method in the TokenManagerERC20 contract on the targetSchain. `addERC20TokenByOwner(originSchainName, originERC20Address, targetERC20Address)`

[IMPORTANT]
The parameters on target TokenManagerERC20.addERC20TokenByOwner() are not symmetric to origin! The only parameter to swap is the first parameter for SchainName.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/erc20/register-target-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc20/register-target-web3.js[]
----
--
====

=== 5. Assign MINTER and BURNER roles to TokenManager on Target.

Now you need to assign the **TokenManagerERC20** contact on your SKALE Chain as the MINTER_ROLE and BURNER_ROLE for the ERC20 clone on the target. With OpenZeppelin's framework, you simply need to execute an AddMinter, AddBurner, and/or grantRole transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--

[source,javascript]
----
include::example$erc20/add-minter-role.js[]
----
--
====

[[transfer]]
== Get Started with S2S ERC20 Transfer

[NOTE]
Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating S2S transfers.

=== 1. S2S Transfer ERC20 From Origin

To send ERC20 tokens from a user's wallet to another SKALE Chain, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/schain/TokenManagers/TokenManagerERC20.sol#L109[transferToSchainERC20] function within the **TokenManagerERC20** IMA contract on the origin chain.  

This method is called from the origin chain to move ERC20 tokens to a target chain.  

The **TokenManagerERC20** contract is predeployed on each SKALE Chain. To get the SKALE Chain ABIs, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/mainnet/IMA[current release page].

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc20/transfer-from-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc20/transfer-from-origin-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To exit ERC20 tokens back to the origin chain, you will need to use the `transferToSchainERC20` function within the **TokenManagerERC20** IMA contract on the target chain, and **specify the erc20Address on the origin chain**.  

The **TokenManagerERC20** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc20/transfer-from-target-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc20/transfer-from-target-web3.js[]
----
--
====
