= SKALE Chain to SKALE Chain ERC1155 Transfer

As a SKALE chain Owner, there are two main steps to managing SKALE Chain to SKALE Chain (S2S) ERC1155 transfer through IMA:

1.  xref:setup[One-time setup to another SKALE Chain]
2.  xref:transfer[Transferring ERC1155 S2S]

Once you have completed step 1 to setup ERC1155 tokens with another chain, end-users can transfer ERC1155 tokens between SKALE Chains.

[[setup]]
== Setup ERC1155 S2S Transfers

The following one-time setup is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Enable Automatic Deploy

include::partial$autodeploy-note.adoc[]

First, enable automatic deploy on the `origin` chain.

[NOTE]
Only the `AUTOMATIC_DEPLOYER_ROLE` may enable or disable automatic deployment.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/automatic-deploy-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
// TODO
----
--
====

=== 2. Connect the target SKALE chain

Add the `target` chain by using `connectSchain` within the **TokenManagerLinker** contract on the `origin` chain.

[NOTE]
Only the `REGISTRAR_ROLE` may execute `connectSchain`.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-web3.js[]
----
--
====

[[transfer]]
== Get Started with S2S ERC1155 Transfer

[NOTE]
Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating S2S transfers.

=== 1. S2S Transfer ERC1155 From Origin

To send ERC1155 tokens from a user's wallet to another SKALE Chain, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/schain/TokenManagers/TokenManagerERC1155.sol#L106-L122[transferToSchainERC1155] function within the **TokenManagerERC1155** IMA contract on the origin chain.  

This method is called from the origin chain to move ERC1155 tokens to a target chain.  

The **TokenManagerERC1155** contract is predeployed on each SKALE Chain. To get the SKALE Chain ABIs, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/mainnet/IMA[current release page].

[NOTE]
It's also possible to transfer a batch of ERC1155 tokens at once. To do that, just pass `tokenIds` and `amounts` arrays instead of `tokenId` and `amount` to `transferToSchain` function.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc1155/transfer-from-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/transfer-from-origin-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To exit ERC1155 tokens back to the origin chain, you will need to use the `transferToSchainERC1155` function within the **TokenManagerERC1155** IMA contract on the target chain, and **specify the erc1155Address on the origin chain**.  

The **TokenManagerERC1155** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[NOTE]
It's also possible to transfer a batch of ERC1155 tokens at once. To do that, just pass `tokenIds` and `amounts` arrays instead of `tokenId` and `amount` to `transferToSchain` function.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc1155/transfer-from-target-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/transfer-from-target-web3.js[]
----
--
====
