= SKALE Chain to SKALE Chain ERC721 Transfer

As a SKALE chain Owner, there are two main steps to managing SKALE Chain to SKALE Chain (S2S) ERC721 transfer through IMA:

1.  xref:setup[One-time setup to another SKALE Chain]
2.  xref:transfer[Transferring ERC721 S2S]

Once you have completed step 1 to setup ERC721 tokens with another chain, end-users can transfer ERC721 tokens between SKALE Chains.

[[setup]]
== Setup ERC721 S2S Transfers

The following one-time setup is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Connect each SKALE Chain

You must connect each chain in both directions by executing two connectSchain() transaction on each respective chain.

⇢ To connect the `target` chain to the `origin` chain, run `connectSchain(targetSchainName)` in **TokenManagerLinker** contract on the `origin` chain. 

⇠ To connect the `origin` chain to the `target` chain, run `connectSchain(originSchainName)` in **TokenManagerLinker** contract on the `target` chain.

[NOTE]
Only the `REGISTRAR_ROLE` in TokenManagerLinker may execute `connectSchain`. So you must be granted with this role on this contract.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-web3.js[]
----
--
====

=== 2. Deploy ERC721 on Origin

Deploy your ERC721 contract on the Origin chain.

[source,javascript]
----
include::example$erc721/token.sol[]
----

=== 3. Deploy ERC721 clone on Target

The ERC721 clone on the target chain MUST have both mint and burn functionalities. If the original ERC721 contract on origin does not have burn functionalities, then you must add burn() to the clone.

[source,javascript]
----
include::example$erc721/token-clone.sol[]
----

=== 4. Register ERC721 in TokenManager on Origin

You need to register the origin token contract using the addERC721TokenByOwner method in the TokenManagerERC721 contract. `addERC721TokenByOwner(targetSchainName, originERC721Address, targetERC721Address)`

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/erc721/register-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc721/register-origin-web3.js[]
----
--
====

=== 5. Register ERC721 clone in TokenManger on Target

You need to register the target token contract using the addERC721TokenByOwner method in the TokenManagerERC721 contract on the targetSchain. `addERC721TokenByOwner(originSchainName, originERC721Address, targetERC721Address)`

[IMPORTANT]
The parameters on target TokenManagerERC721.addERC721TokenByOwner() are not symmetric to origin! The only parameter to swap is the first parameter for SchainName.

[tabs]
====
IMA-JS::
+
--
[source,javascript]
----
include::example$s2s/erc721/register-target-imajs.js[]
----
--
Web3 JS::
+
--
[source,javascript]
----
include::example$s2s/erc721/register-target-web3.js[]
----
--
====

=== 6. Assign MINTER and BURNER roles to TokenManager on Target.

Now you need to assign the **TokenManagerERC721** contact on your SKALE Chain as the MINTER_ROLE and BURNER_ROLE for the ERC721 clone on the target. With OpenZeppelin's framework, you simply need to execute an AddMinter, AddBurner, and/or grantRole transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--
[source,javascript]
----
include::example$erc721/add-minter-role.js[]
----
--
====

[[transfer]]
== Get Started with S2S ERC721 Transfer

[NOTE]
Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating S2S transfers.

=== 1. S2S Transfer ERC721 From Origin

To send ERC721 tokens from a user's wallet to another SKALE Chain, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/schain/TokenManagers/TokenManagerERC721.sol#L106-L122[transferToSchainERC721] function within the **TokenManagerERC721** IMA contract on the origin chain.  

This method is called from the origin chain to move ERC721 tokens to a target chain.  

The **TokenManagerERC721** contract is predeployed on each SKALE Chain. To get the SKALE Chain ABIs, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/mainnet/IMA[current release page].

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc721/transfer-from-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc721/transfer-from-origin-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To exit ERC721 tokens back to the origin chain, you will need to use the `transferToSchainERC721` function within the **TokenManagerERC721** IMA contract on the target chain, and **specify the erc721Address on the origin chain**.  

The **TokenManagerERC721** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc721/transfer-from-target-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc721/transfer-from-target-web3.js[]
----
--
====
