= SKALE Chain to SKALE Chain ERC1155 Transfer

As a SKALE chain Owner, there are two main steps to managing SKALE Chain to SKALE Chain (S2S) ERC1155 transfer through IMA:

1.  xref:setup[One-time setup to another SKALE Chain]
2.  xref:transfer[Transferring ERC1155 S2S]

Once you have completed step 1 to setup ERC1155 tokens with another chain, end-users can transfer ERC1155 tokens between SKALE Chains.

[[setup]]
== Setup ERC1155 S2S Transfers

The following one-time setup is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

=== 1. Connect each SKALE Chain

You must connect each chain in both directions by executing two connectSchain() transaction on each respective chain.

⇢ To connect the `target` chain to the `origin` chain, run `connectSchain(targetSchainName)` in **TokenManagerLinker** contract on the `origin` chain. 

⇠ To connect the `origin` chain to the `target` chain, run `connectSchain(originSchainName)` in **TokenManagerLinker** contract on the `target` chain.


[NOTE]
Only the `REGISTRAR_ROLE` in TokenManagerLinker may execute `connectSchain`. So you must be granted with this role on this contract.

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/connect-chain-web3.js[]
----
--
====

=== 2. Deploy ERC1155 on Origin

Deploy your ERC1155 contract on the Origin chain.

[source,javascript]
----
include::example$erc1155/token.sol[]
----

=== 3. Deploy ERC1155 clone on Target

The ERC1155 clone on the target chain MUST have both mint and burn functionalities. If the original ERC1155 contract on origin does not have burn functionalities, then you must add burn() to the clone.

[source,javascript]
----
include::example$erc1155/token-clone.sol[]
----

=== 4. Register ERC1155 in TokenManager on Origin

You need to register the origin token contract using the addERC1155TokenByOwner method in the TokenManagerERC1155 contract. `addERC1155TokenByOwner(targetSchainName, originERC1155Address, targetERC1155Address)`

[tabs]
====
IMA-JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/register-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/register-origin-web3.js[]
----
--
====

=== 5. Register ERC1155 clone in TokenManger on Target

You need to register the target token contract using the addERC1155TokenByOwner method in the TokenManagerERC1155 contract on the targetSchain. `addERC1155TokenByOwner(originSchainName, originERC1155Address, targetERC1155Address)`

[IMPORTANT]
The parameters on target TokenManagerERC1155.addERC1155TokenByOwner() are not symmetric to origin! The only parameter to swap is the first parameter for SchainName.

[tabs]
====
IMA-JS::
+
--
[source,javascript]
----
include::example$s2s/erc1155/register-target-imajs.js[]
----
--
Web3 JS::
+
--
[source,javascript]
----
include::example$s2s/erc1155/register-target-web3.js[]
----
--
====

=== 6. Assign MINTER and BURNER roles to TokenManager on Target.

Now you need to assign the **TokenManagerERC1155** contact on your SKALE Chain as the MINTER_ROLE and BURNER_ROLE for the ERC1155 clone on the target. With OpenZeppelin's framework, you simply need to execute an AddMinter, AddBurner, and/or grantRole transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--
[source,javascript]
----
include::example$erc1155/add-minter-role.js[]
----
--
====

[[transfer]]
== Get Started with S2S ERC1155 Transfer

[NOTE]
Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating S2S transfers.

=== 1. S2S Transfer ERC1155 From Origin

To send ERC1155 tokens from a user's wallet to another SKALE Chain, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/schain/TokenManagers/TokenManagerERC1155.sol#L106-L122[transferToSchainERC1155] function within the **TokenManagerERC1155** IMA contract on the origin chain.  

This method is called from the origin chain to move ERC1155 tokens to a target chain.  

The **TokenManagerERC1155** contract is predeployed on each SKALE Chain. To get the SKALE Chain ABIs, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/mainnet/IMA[current release page].

[NOTE]
It's also possible to transfer a batch of ERC1155 tokens at once. To do that, just pass `tokenIds` and `amounts` arrays instead of `tokenId` and `amount` to `transferToSchain` function.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc1155/transfer-from-origin-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/transfer-from-origin-web3.js[]
----
--
====

=== 2. Exit from SKALE Chain

To exit ERC1155 tokens back to the origin chain, you will need to use the `transferToSchainERC1155` function within the **TokenManagerERC1155** IMA contract on the target chain, and **specify the erc1155Address on the origin chain**.  

The **TokenManagerERC1155** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[NOTE]
It's also possible to transfer a batch of ERC1155 tokens at once. To do that, just pass `tokenIds` and `amounts` arrays instead of `tokenId` and `amount` to `transferToSchain` function.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
include::example$s2s/erc1155/transfer-from-target-imajs.js[]
----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s/erc1155/transfer-from-target-web3.js[]
----
--
====
