= SKALE Chain to SKALE Chain ERC20 Transfer

As a SKALE Chain Owner, there are two main steps to managing SKALE Chain to SKALE Chain (S2S) ERC20 transfer through IMA:

1.  xref:setup[One-time setup and map your ERC20 tokens to another SKALE Chain]
2.  xref:transfer[Transferring ERC20 using IMA]

Once you have completed step 1 to setup and map your ERC20 tokens, you can then setup transfer flow to allow end-users to transfer ERC20 tokens between SKALE Chains.

[[setup]]
== Setup and Map ERC20 S2S Transfers

The following one-time setup for each ERC20 token is required for SKALE Chains with a default access control policy (default settings are: whitelisting enabled, automatic deployment disabled). For more information on IMA access control, xref:access-control.adoc[see here].

To see a complete Javascript sandbox version of setup, map, and transfer, see <{erc20-sandbox}>

=== 1. Review/Modify the token contract

First, review the origin chain ERC20 token implementation and (if needed) modify a destination chain version of the contract to include `mint` and `burn` functions. These functions are required by IMA to dynamically mint and burn the token on a SKALE chain.

[discrete]
==== Example Origin Chain contract

[source,javascript]
----
include::example$base-erc20-contract.sol[]
----

[discrete]
==== Example Modified SKALE Chain contract

[source,javascript]
----
include::example$modified-erc20-contract.sol[]
----

If you aren't using OpenZeppelin's framework, then you can simply manually add https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC20/ERC20.sol#L233[mintable] and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3178ff942f9f487b9fda2c648aa19e633560adb/contracts/token/ERC20/ERC20.sol#L254[burnable] functions, and finally https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.5.1/contracts/access/roles/MinterRole.sol[add MINTER_ROLE access control]. 

=== 2. Add a Minter Role

Now you need to add the pre-deployed **TokenManagerERC20** contact on your SKALE Chain as the MINTER_ROLE for the modified SKALE Chain contract. With OpenZeppelin's framework, you simply need to execute an AddMinter transaction on the SKALE chain token contract.

[discrete]
==== Example Add Minter Role 

[tabs]
====
Web3 JS::
+
--

[source,javascript]
----
include::example$add-minter-role-erc20.js
----
--
====

For a Javascript sandbox of the minter implementation, see <https://codesandbox.io/s/erc20-transfer-skale-interchain-messaging-agent-forked-w1t5m?file=/src/addMinter.js>

=== 3. Register and connect the new SKALE Chain

Third, you need to register and connect the new SKALE Chain into the origin chain&#39;s Message Proxy using the `registerExtraContract` and `addConnectedChain` methods in the MessageProxyForSchain contract.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
// TODO

----

--

Web3 JS::
+
--
[source, javascript]
----
include::example$s2s-erc20-register-web3.js[]
----
--
====


=== 4. Link the contract across SKALE chains

Fourth, you need to link the two token contracts in the origin chains Token Manager using the  addERC20TokenByOwner method in the TokenManagerERC20 contract.

[NOTE]
Once you link two contracts, you cannot relink the clone.

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
// todo
----

--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s-link-token-manager.js[]
----
--
====

[[transfer]]
== Get Started with S2S ERC20 Transfer

The Interchain Messaging Agent can be used for managing ERC20 tokens between Ethereum and SKALE.  The following steps guide you through a complete transfer from Ethereum to SKALE and back. Be sure to follow any one-time setup and mapping steps described xref:setup[here] before initiating transfers.

link:{erc20-sandbox}[Live ERC20 IMA Demo]

=== 1. S2S Transfer ERC20 From Origin

To send ERC20 tokens from a user's wallet to another SKALE Chain, you will need to use the https://github.com/skalenetwork/IMA/blob/develop/proxy/contracts/schain/TokenManagers/TokenManagerERC20.sol#L109[transferToSchainERC20] function within the **TokenManagerERC20** IMA contract on the origin chain.  

This method is called from the origin chain to move ERC20 tokens into a destination chain.  

The **TokenManagerERC20** contract is predeployed on each SKALE Chain. To get the SKALE Chain ABIs, check out the https://github.com/skalenetwork/skale-network/tree/master/releases/mainnet/IMA[current release page].

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
// todo

----
--

Web3 JS::
+
--

[source,javascript]
----
include::example$s2s-erc20-transfer-from-origin.js[]
----
--
====

=== 2. Exit from SKALE Chain

To exit ERC20 tokens back to the origin chain, you will need to use the exitToMainERC20 function within the **TokenManagerERC20** IMA contract on the SKALE Chain.  

The **TokenManagerERC20** IMA contract is pre-deployed to your SKALE Chain. Please reach out to your account manager to receive the ABIs specific for your SKALE Chain.  

[tabs]
====
IMA-JS::
+
--

[source, javascript]
----
// todo

----
--

Web3 JS::
+
--

[source,javascript]
----
// todo
----
--
====
